// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Parse = require("../../src/parse.js");
var Sinon = require("wonder-bs-sinon/lib/js/src/sinon.js");
var Sinon$1 = require("sinon");
var StringTool = require("./stringTool.js");
var Wonder_jest = require("wonder-bs-jest/lib/js/src/wonder_jest.js");

Wonder_jest.describe("parse", (function (param) {
        var sandbox = Sinon.getSandboxDefaultVal(/* () */0);
        beforeEach((function () {
                sandbox[0] = Sinon$1.sandbox.create();
                return /* () */0;
              }));
        Wonder_jest.describe("parseSegment", (function (param) {
                return Wonder_jest.test("parse segment", (function (param) {
                              return Curry._2(Wonder_jest.Expect[/* Operators */25][/* = */5], Wonder_jest.Expect[/* expect */0](StringTool.removeSegmentDataBlankNewLine(Parse.parseSegment("../src/basic.glsl", "\n         @top\n         precision highp float;\n         @end\n\n         @define\n         #import \"common_vertex\"\n         @end\n\n\n\n         @varDeclare\n\n         varying vec2 v_mapCoord0;\n\n         varying vec2 v_mapCoord1;\n         @end\n\n         @funcDeclare\n         vec3 getDirectionLightDirByLightPos(vec3 lightPos);\n         @end\n\n         @funcDefine\n         vec3 getDirectionLightDirByLightPos(vec3 lightPos){\n             return lightPos - vec3(0.0);\n         }\n         @end\n\n         @body\n         gl_Position = u_pMatrix * u_vMatrix * mMatrix * vec4(a_position, 1.0);\n         @end\n\n         "))), StringTool.removeSegmentDataBlankNewLine(/* tuple */[
                                              "basic",
                                              /* tuple */[
                                                "top",
                                                "precision highp float;"
                                              ],
                                              /* tuple */[
                                                "define",
                                                "#import \"common_vertex\""
                                              ],
                                              /* tuple */[
                                                "varDeclare",
                                                "\nvarying vec2 v_mapCoord0;\n\nvarying vec2 v_mapCoord1;\n    "
                                              ],
                                              /* tuple */[
                                                "funcDeclare",
                                                "\n         vec3 getDirectionLightDirByLightPos(vec3 lightPos);\n    "
                                              ],
                                              /* tuple */[
                                                "funcDefine",
                                                "\n         vec3 getDirectionLightDirByLightPos(vec3 lightPos){\n             return lightPos - vec3(0.0);\n         }\n                    "
                                              ],
                                              /* tuple */[
                                                "body",
                                                "\n         gl_Position = u_pMatrix * u_vMatrix * mMatrix * vec4(a_position, 1.0);\n                    "
                                              ]
                                            ]));
                            }));
              }));
        return Wonder_jest.describe("parseImport", (function (param) {
                      Wonder_jest.test("support one glsl's segment import other glsl's segment", (function (param) {
                              return Curry._2(Wonder_jest.Expect[/* Operators */25][/* = */5], Wonder_jest.Expect[/* expect */0](StringTool.removeBlankNewLine(Parse.parseImport(/* :: */[
                                                      /* tuple */[
                                                        "basic0",
                                                        /* tuple */[
                                                          "top",
                                                          ""
                                                        ],
                                                        /* tuple */[
                                                          "define",
                                                          "\n#import \"basic1\"\ndefine A 1;\n#import \"basic2\"\ndefine B 2;\n    "
                                                        ],
                                                        /* tuple */[
                                                          "varDeclare",
                                                          "\n#import \"basic2\"\n\nvarying vec2 v_mapCoord0;\n\n#import \"basic1\"\n    "
                                                        ],
                                                        /* tuple */[
                                                          "funcDeclare",
                                                          ""
                                                        ],
                                                        /* tuple */[
                                                          "funcDefine",
                                                          ""
                                                        ],
                                                        /* tuple */[
                                                          "body",
                                                          ""
                                                        ]
                                                      ],
                                                      /* :: */[
                                                        /* tuple */[
                                                          "basic1",
                                                          /* tuple */[
                                                            "top",
                                                            ""
                                                          ],
                                                          /* tuple */[
                                                            "define",
                                                            "\ndefine C 3;\n#import \"basic2\"\n    "
                                                          ],
                                                          /* tuple */[
                                                            "varDeclare",
                                                            "\nvarying vec2 v_mapCoord1;\n    "
                                                          ],
                                                          /* tuple */[
                                                            "funcDeclare",
                                                            ""
                                                          ],
                                                          /* tuple */[
                                                            "funcDefine",
                                                            ""
                                                          ],
                                                          /* tuple */[
                                                            "body",
                                                            ""
                                                          ]
                                                        ],
                                                        /* :: */[
                                                          /* tuple */[
                                                            "basic2",
                                                            /* tuple */[
                                                              "top",
                                                              ""
                                                            ],
                                                            /* tuple */[
                                                              "define",
                                                              "\ndefine D 4;\n    "
                                                            ],
                                                            /* tuple */[
                                                              "varDeclare",
                                                              "\nvarying vec2 v_mapCoord2;\n    "
                                                            ],
                                                            /* tuple */[
                                                              "funcDeclare",
                                                              ""
                                                            ],
                                                            /* tuple */[
                                                              "funcDefine",
                                                              ""
                                                            ],
                                                            /* tuple */[
                                                              "body",
                                                              ""
                                                            ]
                                                          ],
                                                          /* [] */0
                                                        ]
                                                      ]
                                                    ]))), StringTool.removeBlankNewLine("\n|>set(\"basic0\",_buildChunk({||},{|defineC3;defineD4;defineA1;defineD4;defineB2;|},{|varyingvec2v_mapCoord2;varyingvec2v_mapCoord0;varyingvec2v_mapCoord1;|},{||},{||},{||}))\n|>set(\"basic1\",_buildChunk({||},{|defineC3;defineD4;|},{|varyingvec2v_mapCoord1;|},{||},{||},{||}))\n|>set(\"basic2\",_buildChunk({||},{|defineD4;|},{|varyingvec2v_mapCoord2;|},{||},{||},{||}))\n"));
                            }));
                      return Wonder_jest.describe("check", (function (param) {
                                    Wonder_jest.test("check circular reference", (function (param) {
                                            return Wonder_jest.Expect[/* toThrowMessage */21]("not allow circular reference(the reference path is basic0=>basic1=>basic2=>basic0)", Wonder_jest.Expect[/* expect */0]((function (param) {
                                                              Parse.parseImport(/* :: */[
                                                                    /* tuple */[
                                                                      "basic0",
                                                                      /* tuple */[
                                                                        "top",
                                                                        ""
                                                                      ],
                                                                      /* tuple */[
                                                                        "define",
                                                                        "\n#import \"basic1\"\ndefine A 1;\n    "
                                                                      ],
                                                                      /* tuple */[
                                                                        "varDeclare",
                                                                        ""
                                                                      ],
                                                                      /* tuple */[
                                                                        "funcDeclare",
                                                                        ""
                                                                      ],
                                                                      /* tuple */[
                                                                        "funcDefine",
                                                                        ""
                                                                      ],
                                                                      /* tuple */[
                                                                        "body",
                                                                        ""
                                                                      ]
                                                                    ],
                                                                    /* :: */[
                                                                      /* tuple */[
                                                                        "basic1",
                                                                        /* tuple */[
                                                                          "top",
                                                                          ""
                                                                        ],
                                                                        /* tuple */[
                                                                          "define",
                                                                          "\ndefine C 3;\n#import \"basic2\"\n    "
                                                                        ],
                                                                        /* tuple */[
                                                                          "varDeclare",
                                                                          ""
                                                                        ],
                                                                        /* tuple */[
                                                                          "funcDeclare",
                                                                          ""
                                                                        ],
                                                                        /* tuple */[
                                                                          "funcDefine",
                                                                          ""
                                                                        ],
                                                                        /* tuple */[
                                                                          "body",
                                                                          ""
                                                                        ]
                                                                      ],
                                                                      /* :: */[
                                                                        /* tuple */[
                                                                          "basic2",
                                                                          /* tuple */[
                                                                            "top",
                                                                            ""
                                                                          ],
                                                                          /* tuple */[
                                                                            "define",
                                                                            "\n#import \"basic0\"\n    "
                                                                          ],
                                                                          /* tuple */[
                                                                            "varDeclare",
                                                                            ""
                                                                          ],
                                                                          /* tuple */[
                                                                            "funcDeclare",
                                                                            ""
                                                                          ],
                                                                          /* tuple */[
                                                                            "funcDefine",
                                                                            ""
                                                                          ],
                                                                          /* tuple */[
                                                                            "body",
                                                                            ""
                                                                          ]
                                                                        ],
                                                                        /* [] */0
                                                                      ]
                                                                    ]
                                                                  ]);
                                                              return /* () */0;
                                                            })));
                                          }));
                                    Wonder_jest.describe("should import fileName, not filePath", (function (param) {
                                            Wonder_jest.test("fileName shouldn't start with ./", (function (param) {
                                                    return Wonder_jest.Expect[/* toThrowMessage */21]("should import fileName, not filePath", Wonder_jest.Expect[/* expect */0]((function (param) {
                                                                      Parse.parseImport(/* :: */[
                                                                            /* tuple */[
                                                                              "basic0",
                                                                              /* tuple */[
                                                                                "top",
                                                                                ""
                                                                              ],
                                                                              /* tuple */[
                                                                                "define",
                                                                                "\n#import \"./src/basic1\"\ndefine A 1;\n    "
                                                                              ],
                                                                              /* tuple */[
                                                                                "varDeclare",
                                                                                ""
                                                                              ],
                                                                              /* tuple */[
                                                                                "funcDeclare",
                                                                                ""
                                                                              ],
                                                                              /* tuple */[
                                                                                "funcDefine",
                                                                                ""
                                                                              ],
                                                                              /* tuple */[
                                                                                "body",
                                                                                ""
                                                                              ]
                                                                            ],
                                                                            /* :: */[
                                                                              /* tuple */[
                                                                                "basic1",
                                                                                /* tuple */[
                                                                                  "top",
                                                                                  ""
                                                                                ],
                                                                                /* tuple */[
                                                                                  "define",
                                                                                  ""
                                                                                ],
                                                                                /* tuple */[
                                                                                  "varDeclare",
                                                                                  ""
                                                                                ],
                                                                                /* tuple */[
                                                                                  "funcDeclare",
                                                                                  ""
                                                                                ],
                                                                                /* tuple */[
                                                                                  "funcDefine",
                                                                                  ""
                                                                                ],
                                                                                /* tuple */[
                                                                                  "body",
                                                                                  ""
                                                                                ]
                                                                              ],
                                                                              /* [] */0
                                                                            ]
                                                                          ]);
                                                                      return /* () */0;
                                                                    })));
                                                  }));
                                            return Wonder_jest.test("fileName shouldn't start with ../", (function (param) {
                                                          return Wonder_jest.Expect[/* toThrowMessage */21]("should import fileName, not filePath", Wonder_jest.Expect[/* expect */0]((function (param) {
                                                                            Parse.parseImport(/* :: */[
                                                                                  /* tuple */[
                                                                                    "basic0",
                                                                                    /* tuple */[
                                                                                      "top",
                                                                                      ""
                                                                                    ],
                                                                                    /* tuple */[
                                                                                      "define",
                                                                                      "\n#import \"../src/basic1\"\ndefine A 1;\n    "
                                                                                    ],
                                                                                    /* tuple */[
                                                                                      "varDeclare",
                                                                                      ""
                                                                                    ],
                                                                                    /* tuple */[
                                                                                      "funcDeclare",
                                                                                      ""
                                                                                    ],
                                                                                    /* tuple */[
                                                                                      "funcDefine",
                                                                                      ""
                                                                                    ],
                                                                                    /* tuple */[
                                                                                      "body",
                                                                                      ""
                                                                                    ]
                                                                                  ],
                                                                                  /* :: */[
                                                                                    /* tuple */[
                                                                                      "basic1",
                                                                                      /* tuple */[
                                                                                        "top",
                                                                                        ""
                                                                                      ],
                                                                                      /* tuple */[
                                                                                        "define",
                                                                                        ""
                                                                                      ],
                                                                                      /* tuple */[
                                                                                        "varDeclare",
                                                                                        ""
                                                                                      ],
                                                                                      /* tuple */[
                                                                                        "funcDeclare",
                                                                                        ""
                                                                                      ],
                                                                                      /* tuple */[
                                                                                        "funcDefine",
                                                                                        ""
                                                                                      ],
                                                                                      /* tuple */[
                                                                                        "body",
                                                                                        ""
                                                                                      ]
                                                                                    ],
                                                                                    /* [] */0
                                                                                  ]
                                                                                ]);
                                                                            return /* () */0;
                                                                          })));
                                                        }));
                                          }));
                                    return Wonder_jest.test("should import fileName without extname", (function (param) {
                                                  return Wonder_jest.Expect[/* toThrowMessage */21]("should import fileName without .glsl", Wonder_jest.Expect[/* expect */0]((function (param) {
                                                                    Parse.parseImport(/* :: */[
                                                                          /* tuple */[
                                                                            "basic0",
                                                                            /* tuple */[
                                                                              "top",
                                                                              ""
                                                                            ],
                                                                            /* tuple */[
                                                                              "define",
                                                                              "\n#import \"basic1.glsl\"\ndefine A 1;\n    "
                                                                            ],
                                                                            /* tuple */[
                                                                              "varDeclare",
                                                                              ""
                                                                            ],
                                                                            /* tuple */[
                                                                              "funcDeclare",
                                                                              ""
                                                                            ],
                                                                            /* tuple */[
                                                                              "funcDefine",
                                                                              ""
                                                                            ],
                                                                            /* tuple */[
                                                                              "body",
                                                                              ""
                                                                            ]
                                                                          ],
                                                                          /* :: */[
                                                                            /* tuple */[
                                                                              "basic1",
                                                                              /* tuple */[
                                                                                "top",
                                                                                ""
                                                                              ],
                                                                              /* tuple */[
                                                                                "define",
                                                                                ""
                                                                              ],
                                                                              /* tuple */[
                                                                                "varDeclare",
                                                                                ""
                                                                              ],
                                                                              /* tuple */[
                                                                                "funcDeclare",
                                                                                ""
                                                                              ],
                                                                              /* tuple */[
                                                                                "funcDefine",
                                                                                ""
                                                                              ],
                                                                              /* tuple */[
                                                                                "body",
                                                                                ""
                                                                              ]
                                                                            ],
                                                                            /* [] */0
                                                                          ]
                                                                        ]);
                                                                    return /* () */0;
                                                                  })));
                                                }));
                                  }));
                    }));
      }));

/*  Not a pure module */
