// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function removeBlankNewLine(str) {
  return str.replace((/[\s\n]+/g), "");
}

function removeSegmentDataBlankNewLine(param) {
  var match = param[6];
  var match$1 = param[5];
  var match$2 = param[4];
  var match$3 = param[3];
  var match$4 = param[2];
  var match$5 = param[1];
  return /* tuple */[
          param[0],
          /* tuple */[
            match$5[0],
            removeBlankNewLine(match$5[1])
          ],
          /* tuple */[
            match$4[0],
            removeBlankNewLine(match$4[1])
          ],
          /* tuple */[
            match$3[0],
            removeBlankNewLine(match$3[1])
          ],
          /* tuple */[
            match$2[0],
            removeBlankNewLine(match$2[1])
          ],
          /* tuple */[
            match$1[0],
            removeBlankNewLine(match$1[1])
          ],
          /* tuple */[
            match[0],
            removeBlankNewLine(match[1])
          ]
        ];
}

exports.removeBlankNewLine = removeBlankNewLine;
exports.removeSegmentDataBlankNewLine = removeSegmentDataBlankNewLine;
/* No side effect */
