// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function createEmpty() {
  return /* array */[];
}

function flatten(arr) {
  return arr.reduce((function (a, b) {
                return a.concat(b);
              }), /* array */[]);
}

exports.createEmpty = createEmpty;
exports.flatten     = flatten;
/* No side effect */
