// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function createEmpty(param) {
  return /* array */[];
}

function flatten(arr) {
  return arr.reduce((function (a, b) {
                return a.concat(b);
              }), /* array */[]);
}

exports.createEmpty = createEmpty;
exports.flatten = flatten;
/* No side effect */
